### ISSUE TITLE
Update VPC module with route tables and different outputs

### ISSUE THREAD

**Issue by frdvo** [devopsacademyau/2020-jun-project1-group3#26]
- Route tables
- Enable DNS resolution and hostnames
- Output subnet IDs

**Comment by jayanath** [comment]
Refactored vpc stack. Renamed the vpc module as _networking_ to be more appropriate. 
Integrated all existing modules except ecs. We will have to refactor that a bit before proceed.
Rebased all the changes with existing master and fixed all merge conflicts. 
Terraform plan worked without any complain. Will run terraform apply in the morning.
